# Generated by Django 4.2 on 2024-12-14 18:48

import bot.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('full_name_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('full_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('full_name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('username_uz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('username_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('username_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[bot.validators.phone_number_validator])),
                ('user_lang', models.CharField(blank=True, max_length=10, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Telegram Username')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('my_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/account/images')),
                ('bio', models.TextField(blank=True, max_length=300, null=True)),
                ('bio_uz', models.TextField(blank=True, max_length=300, null=True)),
                ('bio_en', models.TextField(blank=True, max_length=300, null=True)),
                ('bio_ru', models.TextField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('referral_link', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.ManyToManyField(blank=True, to='account.customuser')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='VIPPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/vippacet/images', verbose_name='Paket Rasm')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Paket Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Paket Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Paket Nomi')),
                ('title', models.CharField(max_length=100, verbose_name='Paket Sarlavhasi')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='Paket Sarlavhasi')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Paket Sarlavhasi')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Paket Sarlavhasi')),
                ('description', models.TextField(verbose_name="To'liq Tarif")),
                ('description_uz', models.TextField(null=True, verbose_name="To'liq Tarif")),
                ('description_en', models.TextField(null=True, verbose_name="To'liq Tarif")),
                ('description_ru', models.TextField(null=True, verbose_name="To'liq Tarif")),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Umumiy Narx')),
                ('duration', models.PositiveIntegerField(verbose_name='Davomiyligi (kun)')),
                ('daily_income', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Kunlik Daromad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VIP Paket',
                'verbose_name_plural': 'VIP Paketlar',
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_until', models.DateTimeField()),
                ('daily_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vippackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='account.customuser')),
            ],
            options={
                'verbose_name': 'User Package',
                'verbose_name_plural': 'User Packages',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/news/images')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_news', to='account.customuser')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
