# Generated by Django 4.2 on 2024-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/account/images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='my_money',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, max_length=50, null=True),
        ),
    ]
