# Generated by Django 4.2 on 2024-12-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_bio_customuser_email_customuser_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio_en',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_ru',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='username'),
        ),
    ]
