# Generated by Django 4.2 on 2024-12-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_news_description_en_news_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='generate_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
