# Generated by Django 4.2 on 2024-12-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_my_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
