# Generated by Django 4.2 on 2024-12-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_customuser_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vippackage',
            name='user',
        ),
    ]
