# Generated by Django 4.2 on 2024-12-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_vippackage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vippackage',
            name='customuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vip_packages', to='account.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.vippackage'),
        ),
    ]
