# Generated by Django 4.2 on 2024-12-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_vippackage_customuser_alter_customuser_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_address_money', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMinSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_sum', models.CharField(max_length=255, verbose_name='order minimum sum')),
            ],
            options={
                'verbose_name': 'Order minimum sum',
                'verbose_name_plural': 'Order minimum sum',
            },
        ),
    ]
