# Generated by Django 4.2 on 2025-01-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_customuser_address_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderminsum',
            name='min_order_sum',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
    ]
