# Generated by Django 4.2 on 2025-01-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='package',
        ),
        migrations.RemoveField(
            model_name='vippackage',
            name='customuser',
        ),
        migrations.CreateModel(
            name='VIPPackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vip_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.vippackage')),
            ],
            options={
                'verbose_name': 'VIP Paket Sotib Olish',
                'verbose_name_plural': 'VIP Paket Sotib Olishlar',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='vip_packages',
            field=models.ManyToManyField(blank=True, related_name='users', through='account.VIPPackagePurchase', to='account.vippackage'),
        ),
    ]
