# Generated by Django 4.2 on 2025-01-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_comment_content_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vippackagepurchase',
            options={'verbose_name': 'VIP Paket Xaridi', 'verbose_name_plural': 'VIP Paket Xaridlari'},
        ),
        migrations.RenameField(
            model_name='vippackagepurchase',
            old_name='vip_package',
            new_name='package',
        ),
        migrations.RenameField(
            model_name='vippackagepurchase',
            old_name='purchase_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_income',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
