# Generated by Django 4.2 on 2025-01-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_vippackagepurchase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vippackage',
            old_name='daily_income',
            new_name='daily_income_vip',
        ),
    ]
