# Generated by Django 4.2 on 2025-01-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_rename_daily_income_vippackage_daily_income_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vippackagepurchase',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
