# Generated by Django 4.2 on 2024-12-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vippacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/vippacet/images', verbose_name='Paket Rasm')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Paket Nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Paket Nomi')),
                ('title', models.CharField(max_length=100, verbose_name='Paket Sarlavhasi')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Paket Sarlavhasi')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Paket Sarlavhasi')),
                ('description', models.TextField(help_text="Paket haqida batafsil ma'lumot.", verbose_name="To'liq Tarif")),
                ('description_en', models.TextField(help_text="Paket haqida batafsil ma'lumot.", null=True, verbose_name="To'liq Tarif")),
                ('description_ru', models.TextField(help_text="Paket haqida batafsil ma'lumot.", null=True, verbose_name="To'liq Tarif")),
                ('price', models.DecimalField(decimal_places=15, help_text='Paketning umumiy narxi.', max_digits=20, verbose_name='Umumiy Narx')),
                ('duration', models.PositiveIntegerField(help_text='Paketning qancha davom etishi (kunlarda).', verbose_name='Davomiyligi (kun)')),
                ('daily_price', models.DecimalField(decimal_places=15, help_text='Paket uchun kunlik narx.', max_digits=20, verbose_name='Kunlik Narx')),
            ],
            options={
                'verbose_name': 'VIP Paket',
                'verbose_name_plural': 'VIP Paketlar',
            },
        ),
    ]
